# analytics-service
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/mydb}
server.port=${SERVER_PORT:8081}
spring.rabbitmq.connection-timeout=10000
